/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.ids.loyaltyplatform;

public class LoyaltyPlatformApplication {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new LoyaltyPlatformApplication().getGreeting());
    }
}
