/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.ids.loyaltyplatform;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        LoyaltyPlatformApplication classUnderTest = new LoyaltyPlatformApplication();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
